language: node_js
node_js:
  - "6"

before_deploy: "echo 'ready?'"
deploy:
  provider: heroku
  api_key:
    secure: 60e2aa89-3ac0-4564-a4e1-8311108482da
  app: twitchlite
after_deploy: "echo 'deployed to heroku!'"